server:
  port: 8082

# MyBatis
mybatis:
  type-aliases-package : com.example.demo.model # vo 위치
  mapper-locations : mybatis/mapper/*.xml # mapper 위치
  cofiguration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace